# Generated by Django 5.1.7 on 2025-03-26 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qpt_public_key', models.CharField(blank=True, max_length=256, null=True)),
                ('qpt_private_key', models.CharField(blank=True, max_length=256, null=True)),
                ('hbar_public_key', models.CharField(blank=True, max_length=256, null=True)),
                ('hbar_private_key', models.CharField(blank=True, max_length=256, null=True)),
                ('recipient_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
