# Generated by Django 5.1.7 on 2025-03-26 10:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_userwallet_hbar_private_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('SEND', 'Send'), ('RECEIVE', 'Receive'), ('WITHDRAW', 'Withdraw')], max_length=10)),
                ('currency', models.CharField(choices=[('QPT', 'QPT'), ('HBAR', 'HBAR')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('recipient_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashgraph', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
