# Generated by Django 5.1.7 on 2025-03-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_userwallet_balance_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallet',
            name='balance',
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='qpt_private_key',
            field=models.CharField(blank=True, editable=False, max_length=256, null=True),
        ),
    ]
